version: "3.9"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile_web
    ports:
      - "80:80"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile_api
    ports:
      - "5000:5000"

  redis:
    image: "redis:latest"
