version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379

  web:
    build:
      context: ./web 
    ports:
      - "3000:3000"

  redis:
    image: redis 
